version: '3.8'
services:
  client-backend:
    image: universe-backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/universe
    restart: on-failure

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: universe
      PGUSER: postgres
      POSTGRES_PASSWORD: 310892
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 5