version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/universe

  postgres:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: universe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 310892
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped