spring:
  web:
    resources:
      static-locations: classpath:/resources/static/**
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:universe}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:310892}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  error:
    include-message: always